version: "3.7"

services:
    nginx:
        image: symfony-nginx
        build:
            context: .
            dockerfile: docker/nginx.Dockerfile
        env_file:
            - .env
        ports:
            - "${APP_PORT}:80"
        volumes:
            - ./:/var/www/app
        links:
            - fpm
        restart: always
        depends_on:
            - fpm
    fpm:
        image: symfony-fpm
        build:
            context: .
            dockerfile: docker/fpm.Dockerfile
            args:
                - INSTALL_XDEBUG=${INSTALL_XDEBUG}
        env_file:
            - .env
        volumes:
            - ./:/var/www/app
        ports:
            - "9000"
        links:
            - db
        restart: always
        depends_on:
            - db
    db:
        image: "mysql:${DB_VERSION:-5.7}"
        ports:
            - "${FORWARD_DB_PORT:-DB_PORT}:${DB_PORT}"
        environment:
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: "${DB_DATABASE}"
            MYSQL_USER: "${DB_USERNAME}"
            MYSQL_PASSWORD: "${DB_PASSWORD}"
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        restart: always

